"""empty message

Revision ID: a96d9b971a07
Revises: 
Create Date: 2021-03-04 16:51:46.325219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96d9b971a07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('hair_color', sa.String(length=250), nullable=True),
    sa.Column('skin_color', sa.String(length=250), nullable=True),
    sa.Column('eye_color', sa.String(length=250), nullable=True),
    sa.Column('birth_year', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=250), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('edited', sa.Date(), nullable=True),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('rotation_period', sa.Integer(), nullable=True),
    sa.Column('orbital_period', sa.Integer(), nullable=True),
    sa.Column('gravity', sa.String(length=250), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('climate', sa.String(length=250), nullable=True),
    sa.Column('terrain', sa.String(length=250), nullable=True),
    sa.Column('surface_water', sa.Integer(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('edited', sa.Date(), nullable=True),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('prophile_photo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fav_character',
    sa.Column('id_FavCharacters', sa.Integer(), nullable=False),
    sa.Column('id_Character', sa.Integer(), nullable=True),
    sa.Column('id_Username', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_Character'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['id_Username'], ['user_table.uid'], ),
    sa.PrimaryKeyConstraint('id_FavCharacters')
    )
    op.create_table('fav_planet',
    sa.Column('id_FavPlanets', sa.Integer(), nullable=False),
    sa.Column('id_Planets', sa.Integer(), nullable=True),
    sa.Column('id_Username', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_Planets'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['id_Username'], ['user_table.uid'], ),
    sa.PrimaryKeyConstraint('id_FavPlanets')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_planet')
    op.drop_table('fav_character')
    op.drop_table('user_table')
    op.drop_table('planet')
    op.drop_table('characters')
    # ### end Alembic commands ###
